### ISSUE TITLE
überlegen wie man sicherstellt dass die dev-dependencies nicht versehentlich committed werden

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/simple_saml#5]
durch die phpstan analyse gibts jetzt zusätzlich zu den saml dependencies die notwendig sind zur laufzeit, damit das addon funktioniert auch noch dev-dependencies.

wenn man lokal `composer update` ausführt bekommt man im `vendor/` ordner beide abhängigkeiten vermischt.
jetzt könnte man sich vertun und die dev dependencies mit ins repo committen, was nicht schön wäre.

todo: überlegen wie man das hinbekommt, damit man nicht die ganzen details kennen muss

**Comment by dergel** [comment]
das wäre wirklich super .. weiss gerade nicht wie ich das übersichtlich für mich hinbekomme
